# Generated by Django 3.0.7 on 2020-08-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='destinations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('img', models.ImageField(default='', upload_to='pics')),
                ('descp', models.TextField(default='')),
                ('price', models.IntegerField(default='')),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
    ]
